python diversity.py \
    --name COLLECTING_EPISODES \
    --env_id Safexp-PointGoalThree0-v0 \
    --n_workers 2 \
    --batch_size 4000 \
    --number_skills 4 \
    --number_epochs 1001 \
    --seed 11 \
    --max_episode_length 1000 \
    --alpha 0.5 \
    --ray
